version: '3.0'
services:
  rasa:
    image: rasa/rasa:2.4.3-spacy-en
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
      - --cors
      - "*"
      - --enable-api

